// flow-typed signature: 8756694f9a2be0f2a183db460f4fe217
// flow-typed version: <<STUB>>/random-dungeon-generator_v^1.0.32/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'random-dungeon-generator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'random-dungeon-generator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'random-dungeon-generator/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'random-dungeon-generator/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'random-dungeon-generator/dist/browserTest' {
  declare module.exports: any;
}

declare module 'random-dungeon-generator/dist/index' {
  declare module.exports: any;
}

declare module 'random-dungeon-generator/dist/index.umd' {
  declare module.exports: any;
}

declare module 'random-dungeon-generator/dist/index.umd.min' {
  declare module.exports: any;
}

declare module 'random-dungeon-generator/webpack.config.babel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'random-dungeon-generator/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'random-dungeon-generator/coverage/lcov-report/prettify'>;
}
declare module 'random-dungeon-generator/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'random-dungeon-generator/coverage/lcov-report/sorter'>;
}
declare module 'random-dungeon-generator/dist/browserTest.js' {
  declare module.exports: $Exports<'random-dungeon-generator/dist/browserTest'>;
}
declare module 'random-dungeon-generator/dist/index.js' {
  declare module.exports: $Exports<'random-dungeon-generator/dist/index'>;
}
declare module 'random-dungeon-generator/dist/index.umd.js' {
  declare module.exports: $Exports<'random-dungeon-generator/dist/index.umd'>;
}
declare module 'random-dungeon-generator/dist/index.umd.min.js' {
  declare module.exports: $Exports<'random-dungeon-generator/dist/index.umd.min'>;
}
declare module 'random-dungeon-generator/webpack.config.babel.js' {
  declare module.exports: $Exports<'random-dungeon-generator/webpack.config.babel'>;
}
