// flow-typed signature: 49ebb11fa1fa9c8cf6fb460fadff098d
// flow-typed version: <<STUB>>/wally-fov_v^0.1.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wally-fov'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wally-fov' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wally-fov/build/field-of-view' {
  declare module.exports: any;
}

declare module 'wally-fov/build/geom/direction-flags' {
  declare module.exports: any;
}

declare module 'wally-fov/build/geom/direction' {
  declare module.exports: any;
}

declare module 'wally-fov/build/geom/index' {
  declare module.exports: any;
}

declare module 'wally-fov/build/geom/mask-rect' {
  declare module.exports: any;
}

declare module 'wally-fov/build/geom/mask' {
  declare module.exports: any;
}

declare module 'wally-fov/build/geom/offset' {
  declare module.exports: any;
}

declare module 'wally-fov/build/geom/rectangle' {
  declare module.exports: any;
}

declare module 'wally-fov/build/geom/size' {
  declare module.exports: any;
}

declare module 'wally-fov/build/index' {
  declare module.exports: any;
}

declare module 'wally-fov/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wally-fov/build/field-of-view.js' {
  declare module.exports: $Exports<'wally-fov/build/field-of-view'>;
}
declare module 'wally-fov/build/geom/direction-flags.js' {
  declare module.exports: $Exports<'wally-fov/build/geom/direction-flags'>;
}
declare module 'wally-fov/build/geom/direction.js' {
  declare module.exports: $Exports<'wally-fov/build/geom/direction'>;
}
declare module 'wally-fov/build/geom/index.js' {
  declare module.exports: $Exports<'wally-fov/build/geom/index'>;
}
declare module 'wally-fov/build/geom/mask-rect.js' {
  declare module.exports: $Exports<'wally-fov/build/geom/mask-rect'>;
}
declare module 'wally-fov/build/geom/mask.js' {
  declare module.exports: $Exports<'wally-fov/build/geom/mask'>;
}
declare module 'wally-fov/build/geom/offset.js' {
  declare module.exports: $Exports<'wally-fov/build/geom/offset'>;
}
declare module 'wally-fov/build/geom/rectangle.js' {
  declare module.exports: $Exports<'wally-fov/build/geom/rectangle'>;
}
declare module 'wally-fov/build/geom/size.js' {
  declare module.exports: $Exports<'wally-fov/build/geom/size'>;
}
declare module 'wally-fov/build/index.js' {
  declare module.exports: $Exports<'wally-fov/build/index'>;
}
declare module 'wally-fov/webpack.config.js' {
  declare module.exports: $Exports<'wally-fov/webpack.config'>;
}
